echo "Cleaning repo first.."
rm -rf dist
rm -rf build
rm -rf dicter.egg-info
rm -rf __pycache__
rm -rf .pytest_cache
rm -rf dicter/__pycache__
rm -rf dicter/.pylint.d
rm -rf dicter/tests/__pycache__
rm -rf tests/__pycache__
rm -rf dicter/utils/__pycache__
rm -rf .pylint.d
rm -rf dicter/data/*.zip
rm -rf dicter/data/*.csv
rm -rf *.js
rm -rf *.html
rm -rf *.css
rm -rf *.dot
rm -rf *.png
rm -rf .coverage*
rm -rf .pkl
