name: Pytest for dicter
on: [push]

jobs:
  test:
    name: Pytest (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
	os: [ubuntu-latest, macos-latest, windows-latest]
	#os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.10]
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Test with pytest
        run: |
          pytest
         